#!/bin/sh

# Define teardown function
teardown() {
    echo "Logging out of Tailscale..."
    tailscale logout
}

# Set trap for SIGTERM and SIGINT
trap teardown SIGTERM SIGINT

# Capture the user to run as
USER=$(whoami)

# Load secrets from ~/.env
if [ -f "/home/$USER/.env" ]; then
    export $(grep -v '^#' /home/$USER/.env | xargs)
fi

# Import authorized SSH keys
mkdir /home/$USER/.ssh
curl -s https://github.com/$(echo $GITHUB_USER | jq -r .login).keys > /home/$USER/.ssh/authorized_keys

# Call GitHub API
GITHUB_USER=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/user)
GITHUB_EMAILS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/user/emails)

# Configure Git
git config --global user.name $(echo $GITHUB_USER | jq .name)
git config --global user.email $(echo $GITHUB_EMAILS | jq .[0].email)
git config --global github.user $(echo $GITHUB_USER | jq .login)
git config --global sendemail.smtpUser $(echo $GITHUB_EMAILS | jq .[0].email)

# Start Tailscale
echo "Starting Tailscale..."
sudo tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055 > /dev/null 2>&1 &
sudo tailscale up --operator=$USER --auth-key=$TAILSCALE_KEY --accept-routes --ssh --hostname=dev

# Start interactive shell
/bin/fish

# Remove ephemeral Tailscale node
teardown